// P2.2 Tester 第三輪集外句組（docs/tester/round3/holdout-th3.txt，62 句）轉成的迴歸期望值。TESTS §0 TH，之後每期都跑。
// fire：Tester 逐條判定為正確的觸發（照 holdout-th3-output.txt），not：Tester 判定的誤觸發（A1–A5）與 Charles 判定 1、2 推出的不觸發。
// id 對應 docs/tester/P2.2-acceptance.md；J1／J2 是 Charles 的判定 1、2（README 決策紀錄）。
// 新增的觸發（lol 後的 G01、省略 ich 的 G05）是照判定 1、2 推出的，不是 Tester 的原始輸出，已在 PHASE_LOG 註明。
const CHAT = /subject ich left out, common in chat/;
export const HOLDOUT3 = [
  // --- W：WhatsApp 真實寫法（25）---
  {
    text: 'hab heut keine zeit, sorry 😕 vllt morgen?', id: 'A1', not: ['G10', 'G09'], say: { G11: /negates the noun “zeit”/ }, notSay: { G11: /stands alone/ },
    cards: [['keine', { lemma: 'kein', pos: 'det' }], ['zeit', { lemma: 'Zeit', pos: 'noun', lowercaseNoun: 'Zeit' }], ['vllt', { colloquial: ['vielleicht'] }]],
  },
  { text: 'bin gleich zu haus, mach schon mal den ofen an', fire: ['G06'], cards: [['haus', { lemma: 'Haus', pos: 'noun' }], ['ofen', { lemma: 'Ofen', pos: 'noun' }]] },
  { text: 'hast du n bisschen milch übrig? meine is leer 🥛', id: 'M-2', fire: ['G09'], cards: [['is', { colloquial: ['ist'] }], ['meine', { lemma: 'mein', pos: 'det' }]] },
  { text: 'isses ok wenn ich später komm?', id: 'M-2', not: ['G09', 'G10'], cards: [['isses', { colloquial: ['ist es'] }], ['komm', { lemma: 'kommen', pos: 'verb', form: /^present tense · 1st person · singular/ }]] },
  { text: 'gibts bei euch noch kuchen oder habt ihr alles aufgegessen 😂', fire: ['G05'], cards: [['gibts', { colloquial: ['gibt es'] }]] },
  { text: 'kannst du mir nen gefallen tun und das paket abholen?', id: 'M-3', fire: ['G04', 'G09'], cards: [['gefallen', { lemma: 'Gefallen', pos: 'noun', gloss: /favou?r/ }]] },
  { text: 'bin grad im zug, netz is mega schlecht', id: 'M-2', fire: ['G08'], not: ['G09', 'G10'], cards: [['is', { colloquial: ['ist'] }]] },
  { text: 'hab den schlüssel vergessen, bist du zuhause?', id: 'J1', not: ['G09', 'G10'], say: { G05: CHAT } },
  { text: 'voll lieb von dir danke!! ❤️', id: 'M-3', not: ['G10'], cards: [['lieb', { lemma: 'lieb', pos: 'adj' }]] },
  { text: 'muss noch schnell einkaufen, brauchst du was?', id: 'A4', fire: ['G04'], not: ['G09'] },
  { text: 'the kids are asleep endlich 😴 wollen wir nen film schauen?', fire: ['G04'] },
  { text: 'hab meine tasche bei dir liegen lassen glaub ich', id: 'A2', not: ['G10', 'G09', 'G01'] },
  { text: 'ruf mich an wenn du da bist', id: 'J1', not: ['G10', 'G09', 'G01'] },
  { text: 'weiß nicht ob ich das schaffe, mal sehen', fire: ['G11'], not: ['G10', 'G09', 'G01'] },
  { text: 'treffen wir uns um halb acht am bahnhof?', fire: ['G08', 'G09'] },
  { text: 'sorry war krank, hab deine nachricht erst jetzt gesehen', id: 'A5', not: ['G01', 'G09', 'G10'], say: { G05: CHAT } },
  { text: 'lol das ist so typisch für ihn 🙈', id: 'J2', say: { G01: /“ist”.*position 2.*“das”/ } },
  { text: 'wie wars beim arzt? alles gut?', id: 'M-2', fire: ['G08'], cards: [['wars', { colloquial: ['war es'] }]] },
  { text: 'hab dir die fotos geschickt, schau mal', id: 'A2', not: ['G10', 'G09', 'G01'], say: { G05: CHAT } },
  { text: 'can you pick up the kids? ich schaff es heute nicht rechtzeitig', fire: ['G11'] },
  { text: 'nimmst du den regenschirm mit? soll heute regnen ☔', fire: ['G04', 'G06', 'G09'] },
  { text: 'die kleinen schlafen schon, kannst leise reinkommen', id: 'M-3', fire: ['G04'], cards: [['kleinen', { lemma: 'klein', pos: 'adj', posLabel: /used as a noun/, form: /^plural/ }]] },
  { text: 'hab ihr gesagt dass wir morgen später kommen', id: 'J1', not: ['G10', 'G09', 'G01'] },
  { text: 'gibt\'s was neues bei dir?', not: ['G10'] },
  { text: 'freu mich schon auf samstag!! 🎉', id: 'A3', not: ['G10', 'G09', 'G01'] },
  // --- O：官方信件／表格（17）---
  { text: 'Sehr geehrte Frau Nguyen, vielen Dank für Ihre Anfrage vom 3. September.', fire: ['G08'], sentences: 1 },
  { text: 'Bitte beachten Sie, dass die Frist am 30.11.2026 abläuft.', fire: ['G02', 'G08'] },
  { text: 'Wir bitten Sie, die fehlenden Unterlagen bis spätestens Ende des Monats einzureichen.', fire: ['G01', 'G14'] },
  { text: 'Ihr Termin bei der Ausländerbehörde findet am Dienstag um 9:30 Uhr statt.', fire: ['G06', 'G08'] },
  { text: 'Bringen Sie bitte Ihren Reisepass und ein aktuelles biometrisches Foto mit.', fire: ['G06'] },
  { text: 'Sollten Sie den Termin nicht wahrnehmen können, sagen Sie ihn bitte rechtzeitig ab.', fire: ['G04', 'G06', 'G11'] },
  { text: 'Ihr Antrag wurde geprüft und genehmigt.', fire: ['G01', 'G13'] },
  { text: 'Die Gebühr in Höhe von 50 Euro ist innerhalb von 14 Tagen zu überweisen.', fire: ['G14'] },
  {
    text: 'Wir weisen Sie darauf hin, dass unvollständige Anträge nicht bearbeitet werden.', id: 'M-3', fire: ['G02', 'G11', 'G13'],
    cards: [['weisen', { lemma: 'weisen', pos: 'verb' }]],
  },
  { text: 'Bei Fragen erreichen Sie uns montags bis freitags zwischen 8 und 12 Uhr.', fire: ['G01'] },
  { text: 'Bitte geben Sie bei der Überweisung Ihr Aktenzeichen an.', fire: ['G07'] },
  { text: 'Hiermit bestätigen wir den Eingang Ihres Schreibens.', fire: ['G01'] },
  { text: 'Leider können wir Ihren Antrag in der jetzigen Form nicht bearbeiten.', fire: ['G01', 'G04', 'G07', 'G11'] },
  { text: 'Bitte füllen Sie das beigefügte Formular aus und senden Sie es an uns zurück.', not: ['G10'] },
  { text: 'Die Anmeldung muss innerhalb von zwei Wochen nach dem Einzug erfolgen.', fire: ['G01', 'G04', 'G07'] },
  { text: 'Sehr geehrter Herr Schulz, anbei erhalten Sie die gewünschten Dokumente.', not: ['G10'] },
  { text: 'Der Betrag wird Ihrem Konto gutgeschrieben.', fire: ['G01'] },
  // --- L：A1–B1 長句（20）---
  { text: 'Nachdem wir den ganzen Tag gewandert waren, haben wir uns in einem kleinen Gasthaus ausgeruht.', fire: ['G02', 'G05', 'G07'] },
  { text: 'Wenn ich mehr Geld hätte, würde ich im Sommer nach Portugal fliegen.', fire: ['G02', 'G08', 'G12'] },
  { text: 'Das Museum, das vor hundert Jahren eröffnet wurde, wird gerade renoviert.', fire: ['G03', 'G13'] },
  {
    text: 'Ich habe vergessen, dir zu sagen, dass der Kurs morgen ausfällt.', id: 'M-3', fire: ['G01', 'G02', 'G05', 'G14'],
    cards: [['ausfällt', { lemma: 'ausfallen', pos: 'verb', firstGloss: /cancel/ }]],
  },
  { text: 'Obwohl es stark geregnet hat, sind die Kinder draußen geblieben.', fire: ['G02', 'G05'] },
  { text: 'Kannst du mir erklären, wie man diese Maschine einschaltet?', fire: ['G04', 'G09'] },
  {
    text: 'Der Brief ist gestern von der Post zugestellt worden.', id: 'M-3', fire: ['G01', 'G05', 'G07'],
    cards: [['zugestellt', { lemma: 'zustellen', pos: 'verb', firstGloss: /deliver/ }]],
  },
  { text: 'Sie hat mir versprochen, dass sie pünktlich zurückkommt.', fire: ['G01', 'G02', 'G05'] },
  { text: 'Wir hätten früher losfahren sollen, dann wären wir nicht im Stau stecken geblieben.', fire: ['G01', 'G08', 'G11', 'G12'] },
  { text: 'Er fragt, ob wir am Wochenende beim Umzug helfen könnten.', fire: ['G01', 'G02', 'G04', 'G08', 'G12'] },
  {
    text: 'Weil der Aufzug kaputt ist, müssen alle Bewohner die Treppe nehmen.', id: 'M-3', fire: ['G02', 'G04'],
    cards: [['Aufzug', { lemma: 'Aufzug', pos: 'noun', firstGloss: /elevator|lift/ }]],
  },
  { text: 'Das Essen, das du gekocht hast, schmeckt wirklich fantastisch.', fire: ['G03'] },
  { text: 'Bevor du das Haus verlässt, mach bitte alle Fenster zu.', fire: ['G02', 'G06'] },
  { text: 'Meine Nachbarin, deren Hund jeden Morgen bellt, zieht nächsten Monat aus.', fire: ['G03', 'G06'] },
  { text: 'Es wäre schön, wenn du uns öfter besuchen könntest.', fire: ['G01', 'G02', 'G04', 'G12'] },
  { text: 'In der Schule wird heute über das neue Projekt gesprochen.', fire: ['G01', 'G07', 'G13'] },
  { text: 'Ich weiß nicht, warum er so früh aufgehört hat.', fire: ['G01', 'G11'] },
  { text: 'Seit wir hier wohnen, haben wir viele nette Leute kennengelernt.', fire: ['G05'] },
  { text: 'Unsere Tochter hat sich über das Geschenk sehr gefreut.', fire: ['G01', 'G05', 'G07'] },
  { text: 'Ohne deine Hilfe hätte ich die Prüfung nicht bestanden.', fire: ['G01', 'G11', 'G12'] },
];
