// P2.3 Tester 第四輪集外句組（docs/tester/round4/whatsapp4.txt，40 句 WhatsApp）轉成的迴歸期望值。TESTS §0 TH，之後每期都跑。
// fire：Tester 判定正確的觸發（whatsapp4-output.txt）；word：字形規則；cards：功能詞與一般字的首要讀法（P2.4 修正項）。
// id 對應 docs/tester/P2.3-acceptance.md 的問題編號。
// 新增的觸發（G06 的 hol … ab、komm … nach、hör auf zu …）是 P2.4 第 5 項的修正，不是 Tester 的原始輸出。
export const HOLDOUT4 = [
  {
    text: 'bin grad im bus, komme so in 20 min 🚌', id: '6', fire: ['G08'], not: ['G10', 'G09', 'G01'],
    cards: [['grad', { colloquial: ['gerade'], lemma: 'gerade', pos: 'adv' }], ['min', { colloquial: ['Minute'], lemma: 'Minute', pos: 'noun' }]],
  },
  { text: 'hast du den schlüssel mitgenommen?', fire: ['G05', 'G09'] },
  { text: 'ok dann bis morgen 😘', not: ['G01', 'G09', 'G10'] },
  { text: 'sorry hab dein handy nicht gehört', fire: ['G05', 'G11'], not: ['G01', 'G10'] },
  { text: 'lol das is ja voll peinlich 😂', fire: ['G01'] },
  { text: 'kannst du vllt noch brot mitbringen?', fire: ['G04', 'G09'] },
  { text: 'na wie wars beim arzt?', fire: ['G08'] },
  { text: 'ja passt, mach ich später', not: ['G10', 'G09'] },
  { text: 'gibts heute abend noch pizza oder nicht', fire: ['G11'] },
  { text: 'hab n termin um 3, danach bin ich frei', not: ['G10'] },
  { text: 'bring bitte die wäsche rein!', fire: ['G10'] },
  { text: 'schreib mir wenn du da bist', not: ['G10'] },
  { text: 'hast nen moment? muss kurz was fragen', fire: ['G04'], not: ['G09', 'G10'] },
  { text: 'the kids are asleep, kannst leise reinkommen', fire: ['G04'] },
  { text: 'ok cool, see you later 👋', not: ['G01', 'G10'] },
  { text: 'weiß noch nicht ob ich heute kann', fire: ['G11'], not: ['G01', 'G10'] },
  { text: 'findest du das auch komisch?', id: '2', fire: ['G09'], cards: [['das', { lemma: 'das', pos: 'pron' }]] },
  { text: 'geh schon mal vor, ich komm gleich nach!', id: '7', fire: ['G10'], say: { G06: /nachkommen/ } },
  { text: 'ist jemand zuhause? hab meinen schlüssel vergessen 🙈', id: '6', fire: ['G05', 'G09'], cards: [['zuhause', { lemma: 'zuhause', pos: 'adv', gloss: /at home/ }]] },
  { text: 'war echt ein schöner abend, danke euch ❤️', not: ['G01', 'G10'] },
  { text: 'sorry bin zu spät, der zug hatte verspätung', not: ['G01', 'G10', 'G09'] },
  { text: 'mach dir keine sorgen, alles gut', fire: ['G11'] },
  { text: 'kommst du morgen mit zum markt?', id: '1', fire: ['G08', 'G09'], word: [['kommst', { notSay: /komms-/ }]] },
  { text: 'na klar, wann treffen wir uns?', not: ['G09'] },
  { text: 'hab vergessen milch zu kaufen 🙄', fire: ['G14'], not: ['G10'] },
  { text: 'bitte vergiss nicht den müll rauszubringen', fire: ['G11', 'G14'] },
  { text: 'ja ne, das geht leider nicht', id: '3', fire: ['G11'], cards: [['ne', { lemma: 'nein', pos: 'intj' }], ['das', { lemma: 'das', pos: 'pron' }]] },
  { text: 'lol hab grad voll den lachflash', not: ['G10'] },
  { text: 'hast du lust auf kino am freitag?', fire: ['G08', 'G09'] },
  { text: 'ich hol die kinder heute ab, du musst nicht fahren', id: '7', fire: ['G04', 'G11'], say: { G06: /abholen/ }, word: [['musst', { notSay: /mus-/ }]] },
  { text: 'kann sein dass es später wird', not: ['G10', 'G09'] },
  { text: 'ruf an wenn was is', not: ['G10'] },
  { text: 'ok hab verstanden 👍', fire: ['G05'] },
  { text: 'wollte nur kurz sagen dass ich dich lieb hab', not: ['G10', 'G01'] },
  { text: 'bin total müde heute, geh früh schlafen', not: ['G10', 'G01'] },
  { text: 'meld dich einfach wenn du zeit hast', not: ['G10'] },
  { text: 'na dann viel spaß euch beiden 🎉', not: ['G10'] },
  { text: 'sorry for the late reply, war den ganzen tag unterwegs', id: '5', cards: [['ganzen', { lemma: 'ganz', pos: 'adj', notPosLabel: /used as a noun/ }]] },
  {
    text: 'kannst du mir das rezept schicken? das war so lecker', id: '4', fire: ['G01', 'G04', 'G09'],
    cards: [['lecker', { lemma: 'lecker', pos: 'adj' }], ['das', { lemma: 'der', pos: 'article' }], ['das', { lemma: 'das', pos: 'pron' }, 1]],
  },
  { text: 'hör auf zu lachen! 😅', id: '7', fire: ['G10', 'G14'], say: { G06: /aufhören/ } },
];
